name: Anyka Bidirectional Audio
version: "2.0.7"
slug: anyka_audio
description: Bidirectional audio for Anyka cameras (single and multi-camera)
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:microphone-message
panel_title: Anyka Audio
options:
  cameras: []
  log_level: info
schema:
  cameras:
    - id: str
      ip: str
      talk_port: int?
      talk_mode: list(ptt|full)?
  log_level: list(trace|debug|info|warning|error)
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface and API
audio: true
